import type { Metadata } from 'next'
import './globals.css'
import './upgrade.css'
import './review-images.css'
import './community-reviews.css'
import './admin/admin.css'
import './brand-partners.css'
import './theme.css'
import './live-votes.css'
import './strain-library.css'
import './strain-library-desktop.css'
import './strain-library-laptop.css'
import './canna-card.css'
import './motion.css'
import './canna-branding.css'
import './layout-polish.css'
import './mascot-inline.css'
import './gas-pass.css'
import './canna-education.css'
import './star-pulse.css'
import './futuristic-polish.css'
import './daily-polish.css'
import './mass-craft-partner.css'
import './noticeable-upgrade.css'
import './live-community-visuals.css'
import './live-feed-readability.css'
import './canna-social-maps.css'
import './canna-social-maps-logo.css'
import './final-ui-fix.css'
import './premium-ui-fix.css'
import './voter-experience.css'
import './voter-feed-final.css'
import './voter-feed-nuclear.css'
import './strain-library-desktop-fix.css'
import './strain-library-desktop-override.css'
import './strain-library-desktop-premium.css'
import './strain-library-desktop-premium-final.css'
import './live-vote-card-images.css'
import './canna-social-maps-premium.css'
import './canna-social-maps-major-upgrade.css'
import './canna-social-maps-motion.css'
import './canna-social-maps-futuristic.css'
import './canna-social-maps-floating-fix.css'
import './live-vote-cards-premium.css'
import './live-voter-motion.css'
import CannaBranding from '@/components/canna-branding'
import LiveVotes from '@/components/live-votes'
import StrainLibrary from '@/components/strain-library'
import CannaSocialCard from '@/components/canna-social-card'
import CommunityReviews from '@/components/community-reviews'
import CannaMascot from '@/components/canna-mascot'
import CannaEducation from '@/components/canna-education'
import CannaSocialMaps from '@/components/canna-social-maps'
import ThemeToggle from '@/components/theme-toggle'
import AgeGate from '@/components/age-gate'

export const metadata: Metadata = {
  title: 'Canna Social — The People’s Cannabis Platform',
  description: 'Discover, vote, review, and connect around cannabis culture and strain knowledge.'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <html lang="en"><body><CannaBranding />{children}<LiveVotes /><StrainLibrary /><CannaEducation /><CannaSocialCard /><CommunityReviews /><CannaMascot /><CannaEducation /><CannaSocialMaps /><ThemeToggle /><AgeGate /></body></html>
}
