'use client'
import { FormEvent, useState } from 'react'

const partners = [
 {name:'No. 9 Collection',tag:'CANNABIS COLLECTION',mark:'N°9',tone:'gold'},
 {name:"Gibby's Craft Cannabis",tag:'CRAFT CANNABIS',mark:"GIBBY'S",tone:'green'},
 {name:'Canna World',tag:'CANNABIS MEDIA',mark:'CANNA\nWORLD',tone:'forest'},
 {name:'Comm Ave Canna',tag:'BROOKLINE • MA',mark:'COMM AVE\nCANNA',tone:'lime'},
]
const networkTypes=['Cannabis Brands','Dispensaries','Creators & Reviewers','Media & Events','Community Voices']

export default function BrandPartners(){
 const [open,setOpen]=useState(false),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [form,setForm]=useState({brand:'',contact:'',email:'',website:'',category:'',goal:'',budget:'',message:''})
 const update=(k:string,v:string)=>setForm(f=>({...f,[k]:v}))
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/brand-partner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to send');setSent(true)}catch(e){setError(e instanceof Error?e.message:'Unable to send')}finally{setBusy(false)}}
 return <section className="brand-partners-page">
  <div className="network-banner"><div className="network-banner-star">✦</div><div><strong>CANNA SOCIAL BRAND NETWORK</strong><span>PARTICIPATING BRANDS • PEOPLE • CREATORS • INDUSTRY PARTNERS</span></div><button onClick={()=>setOpen(true)}>JOIN THE NETWORK →</button></div>
  <div className="brand-partners-hero shell">
   <div><a className="partners-back" href="/">← Back to Canna Social</a><p className="eyebrow">THE CANNA SOCIAL NETWORK</p><h1>Meet the brands<br/><span>behind the culture.</span></h1><p className="partners-lede">Canna Social connects cannabis brands, media, dispensaries, creators and community voices with an audience built around discovery, reviews and public voting.</p><div className="partner-hero-stats"><div><strong>04</strong><small>Participating brands</small></div><div><strong>100+</strong><small>Strains in our library</small></div><div><strong>∞</strong><small>Network growing</small></div></div></div>
   <div className="partners-orbit"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="orbit-star">✦</div><div className="orbit-core"><span>CANNA</span><strong>SOCIAL</strong><small>BRAND NETWORK</small></div></div>
  </div>
  <div className="shell network-strip"><div><p className="eyebrow">WHO'S IN THE NETWORK</p><h2>More than brands.<br/><span>It's a community.</span></h2></div><div className="network-type-grid">{networkTypes.map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div></div>
  <div className="shell partner-showcase">
   <div className="section-head"><div><p className="eyebrow">PARTICIPATING BRAND NETWORK</p><h2>Brands we<br/><span>work with.</span></h2><p className="section-lede">These are brands and organizations currently connected to the Canna Social ecosystem. More partnerships are being added.</p></div><span className="live-pill">● NETWORK ACTIVE</span></div>
   <div className="partner-grid">{partners.map((p,i)=><article className={`partner-tile ${p.tone}`} key={p.name}><div className="partner-tile-top"><span className="partner-badge">PARTNER {String(i+1).padStart(2,'0')}</span><span>✦</span></div><div className="partner-mark">{p.mark.split('\n').map((line,j)=><span key={j}>{line}</span>)}</div><div className="partner-tile-bottom"><strong>{p.name}</strong><small>{p.tag}</small><em>PARTICIPATING NETWORK</em></div></article>)}<article className="partner-tile upcoming"><div className="partner-tile-top"><span className="partner-badge">NEXT UP</span><span>+</span></div><div className="partner-mark"><span>YOUR</span><span>BRAND</span></div><div className="partner-tile-bottom"><strong>Coming soon.</strong><small>New partners are being added</small><em>APPLY TO PARTICIPATE</em></div></article></div>
   <div className="partner-network-note"><div><span className="network-star">✦</span><div><b>The network is growing.</b><p>Brands, dispensaries, creators, reviewers and industry voices can connect with Canna Social to build something the community wants to talk about.</p></div></div><button className="primary" onClick={()=>setOpen(true)}>Work with Canna Social →</button></div>
  </div>
  <div className="shell people-network"><div className="people-network-copy"><p className="eyebrow">PEOPLE • CREATORS • COMMUNITY</p><h2>The people make<br/><span>the network.</span></h2><p>We're building a network around the people who review, create, educate, cover events and keep cannabis culture moving. This section will continue to grow as new participating voices join Canna Social.</p></div><div className="people-cards"><div><span>✦</span><b>REVIEWERS</b><small>Real opinions. Real votes.</small></div><div><span>✦</span><b>CREATORS</b><small>Stories, culture & content.</small></div><div><span>✦</span><b>COMMUNITY</b><small>Millions of voices, one platform.</small></div></div></div>
  <div className="shell partner-collab"><div className="partner-collab-copy"><p className="eyebrow">FOR CANNABIS BRANDS & INDUSTRY PARTNERS</p><h2>Put your brand<br/><span>in the conversation.</span></h2><p>Want Canna Social to review, feature, market or promote your brand? Reach out for reviews, community features, media, events and promotional collaborations.</p><div className="partner-points"><span>✦ Brand features</span><span>✦ Review opportunities</span><span>✦ Community promotion</span><span>✦ Event coverage</span></div><button className="primary" onClick={()=>setOpen(true)}>Start a collaboration →</button></div><div className="partner-card"><span className="partner-orb">CS</span><p>CANNA SOCIAL × BRANDS</p><strong>Let's build<br/>something people<br/>want to talk about.</strong><small>Partnership & collaboration inquiries</small></div></div>
  {open&&<div className="partner-modal-backdrop" onClick={()=>setOpen(false)}><div className="partner-modal" onClick={e=>e.stopPropagation()}><button className="partner-close" onClick={()=>setOpen(false)}>×</button>{sent?<div className="partner-success"><span>✓</span><p className="eyebrow">MESSAGE RECEIVED</p><h3>We'll be in touch.</h3><p>Your collaboration inquiry was sent to the Canna Social team.</p><button className="primary" onClick={()=>setOpen(false)}>Back to Canna Social</button></div>:<><p className="eyebrow">BRAND COLLABORATION INTAKE</p><h3>Promote your brand on Canna Social.</h3><p className="muted">Tell us about your brand and what you want to build with us. We'll review your inquiry and follow up.</p><form onSubmit={submit}><div className="partner-form-grid"><input required placeholder="Brand name" value={form.brand} onChange={e=>update('brand',e.target.value)}/><input required placeholder="Your name" value={form.contact} onChange={e=>update('contact',e.target.value)}/><input required type="email" placeholder="Business email" value={form.email} onChange={e=>update('email',e.target.value)}/><input placeholder="Website / Instagram" value={form.website} onChange={e=>update('website',e.target.value)}/><select required value={form.category} onChange={e=>update('category',e.target.value)}><option value="">Brand category</option><option>Flower</option><option>Pre-Rolls</option><option>Edibles</option><option>Concentrates</option><option>Accessories</option><option>Dispensary</option><option>Other</option></select><select value={form.goal} onChange={e=>update('goal',e.target.value)}><option value="">What are you interested in?</option><option>Product review</option><option>Brand feature</option><option>Advertising / promotion</option><option>Event coverage</option><option>Long-term partnership</option><option>Not sure yet</option></select></div><input placeholder="Estimated promotional budget (optional)" value={form.budget} onChange={e=>update('budget',e.target.value)}/><textarea required rows={4} placeholder="Tell us about your brand and what you want Canna Social to help promote..." value={form.message} onChange={e=>update('message',e.target.value)}/>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?'Sending…':'Send collaboration inquiry →'}</button></form><p className="direct-email">Or email <a href="mailto:tyrelle@commavecanna.com">tyrelle@commavecanna.com</a></p></>}</div></div>}
 </section>
}