'use client'

import { useEffect, useMemo, useState } from 'react'

// Stable Wikimedia redirects are used instead of fragile Special:FilePath URLs.
// The visual fallback keeps every card branded even if a remote image ever fails.
const photos = [
 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cannabis_macro.JPG',
 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Macro_cannabis_bud.jpg',
 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cannabis%20Closeup%2001.jpg',
 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cannabis%20Closeup%2003.jpg',
 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cannabis%20Colors%20Macro.jpg',
 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cannabis%20buds.jpg',
 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Marijuana%20flower.jpg',
 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cannabis%20flower.jpg',
 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Dank%20Nug%20Xyren.jpg',
 'https://commons.wikimedia.org/wiki/Special:Redirect/file/White%20Rhino%20Dub%20Macro.JPG'
]
const names = ['Pink Runtz','Super Lemon Haze','Jelly Donutz','Blue Dream','Wedding Cake','Gelato 41','OG Kush','Granddaddy Purple','Runtz','Sour Diesel','Northern Lights','Gorilla Glue #4','Zkittlez','White Widow','Acapulco Gold','Gelato 33','Sunset Sherbet','Animal Cookies','Girl Scout Cookies','Biscotti','MAC 1','Dosidos','Ice Cream Cake','Cereal Milk','Gary Payton','Permanent Marker','Jealousy','Oreoz','Gushers','Lemon Cherry Gelato','Strawberry Banana','Jack Herer','Green Crack','AK-47','Bruce Banner','Chemdawg','Trainwreck','Durban Poison','Pineapple Express','Tangie','Mimosa','Amnesia Haze','Ghost Train Haze','Purple Haze','LA Confidential','Kosher Kush','Skywalker OG','Fire OG','Grape Ape','Forbidden Fruit','Blackberry Kush','Blue Cheese','Bubblegum','Godfather OG','GMO','Donny Burger','Meat Breath','Motor Breath','London Pound Cake','Rainbow Belts','Cherry Pie','Apple Fritter','Kush Mints','Wedding Crasher','Lava Cake','White Runtz','Black Runtz','Zoap','Super Boof','RS11','Grape Gas','Gas Face','Lemon Tree','Blueberry Muffin','Purple Punch','Banana Cream','Papaya Cake','Mango Kush','Sour Tangie','Chem 91','Strawberry Diesel','NYC Diesel','Super Silver Haze','Golden Goat','Chocolope','Jack the Ripper','Agent Orange','Black Cherry Gelato','Koffin Kandy','Blueberry OG','Cherry Gelato','Rainbow Sherbet','Tropicana Cookies','Strawberry Cough','Gelato Mintz','Animal Mints','Cakes & Cream','Peanut Butter Breath','Platinum OG','Black Cherry Soda','Purple Urkle','Sundae Driver','Grape Pie','Maui Wowie','Hawaiian Snow','Lemon Skunk','Pineapple Chunk','Critical Mass','White Rhino','Cheese','AK-48','Blue Cheese Cake','Bubble Kush','Cookie Monster','Death Star','Alien OG','Black Diamond','Cali Orange','Clementine','Headband','Haze','Kush Cake','Lemon Pound Cake','Mendo Breath','Motorbreath #15','Orange Cookies','Purple Gelato','Sour Cookies','Strawberry Fields','Sunset Octane','Tangerine Dream','Vanilla Frosting','Wedding Gelato','Y Griega','Zookies']
const strains = Array.from(new Set(names)).map((name, i) => [name, 1284 - i * 4] as [string, number])
const activity = ['community voting is live','a new GAS vote landed','the community is voting','a new PASS vote landed','live voting is active']
const industries = ['Cannabis marketing','Cannabis sales / retail','Cultivation / growing','Brand / product company','Dispensary','Cannabis media / content','Cannabis events','Cannabis technology','Cannabis education','Other cannabis industry']
const hash = (s: string) => { let h = 0; for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0; return h }
type Voter = { name: string; action: 'GAS' | 'PASS'; strain: string }
type PendingVote = { name: string; type: 'GAS' | 'PASS' }
type VoteSuccess = { name: string; type: 'GAS' | 'PASS' }

export default function LiveVotes() {
 const [hydrated,setHydrated]=useState(false); const [strainVotes,setStrainVotes]=useState<Record<string,'gas'|'pass'>>({}); const [liveBump,setLiveBump]=useState<Record<string,number>>({}); const [feedIndex,setFeedIndex]=useState(0); const [showAll,setShowAll]=useState(false); const [filter,setFilter]=useState<'all'|'trending'|'my'>('all'); const [sessionVotes,setSessionVotes]=useState(0); const [voterName,setVoterName]=useState(''); const [voterIndustry,setVoterIndustry]=useState(''); const [ageConfirmed,setAgeConfirmed]=useState(false); const [voterVerified,setVoterVerified]=useState(false); const [pendingVote,setPendingVote]=useState<PendingVote|null>(null); const [voterFeed,setVoterFeed]=useState<Voter[]>([]); const [lastAction,setLastAction]=useState(''); const [voteSuccess,setVoteSuccess]=useState<VoteSuccess|null>(null)
 useEffect(()=>{setHydrated(true)},[])
 const pool=useMemo(()=>strains.slice(0,showAll?strains.length:36),[showAll]); const filteredPool=useMemo(()=>filter==='my'?pool.filter(([name])=>!!strainVotes[name]):filter==='trending'?pool.slice(0,12):pool,[filter,pool,strainVotes]); const visible=filteredPool.slice(0,showAll?30:18)
 useEffect(()=>{const timer=window.setInterval(()=>setFeedIndex(i=>(i+1)%Math.max(1,pool.length)),7000); return()=>window.clearInterval(timer)},[pool.length])
 useEffect(()=>{if(!pendingVote)return; const frame=window.requestAnimationFrame(()=>{document.getElementById('canna-voter-access')?.scrollIntoView({behavior:'instant',block:'center',inline:'nearest'}); window.scrollTo({top:Math.max(0,window.scrollY),behavior:'instant'})}); return()=>window.cancelAnimationFrame(frame)},[pendingVote])
 function addVoter(entry:Voter){setVoterFeed(feed=>[entry,...feed].slice(0,6))}
 function showVoteSuccess(name:string,type:'GAS'|'PASS'){setLastAction(`Your ${type} vote on ${name} is counted`);setVoteSuccess({name,type});window.setTimeout(()=>setVoteSuccess(current=>current?.name===name&&current?.type===type?null:current),2200)}
 function recordStrainVote(name:string,type:'GAS'|'PASS',displayName:string){if(strainVotes[name])return;setStrainVotes(v=>({...v,[name]:type==='GAS'?'gas':'pass'}));setLiveBump(v=>({...v,[name]:(v[name]||0)+1}));setSessionVotes(n=>n+1);addVoter({name:displayName,action:type,strain:name});showVoteSuccess(name,type)}
 function openStrainVote(name:string,type:'gas'|'pass'){if(!hydrated||strainVotes[name])return;if(voterVerified&&voterName.trim()){recordStrainVote(name,type.toUpperCase() as 'GAS'|'PASS',voterName.trim());return}setPendingVote({name,type:type.toUpperCase() as 'GAS'|'PASS'});setAgeConfirmed(false)}
 function submitFirstVote(){if(!hydrated||!pendingVote||!ageConfirmed||!voterName.trim()||!voterIndustry)return;const pending=pendingVote;const displayName=voterName.trim();setVoterVerified(true);setPendingVote(null);setAgeConfirmed(false);recordStrainVote(pending.name,pending.type,displayName)}
 const totalLive=visible.reduce((sum,[name,count])=>sum+count+(liveBump[name]||0),0); const feedStrain=pool[feedIndex%Math.max(1,pool.length)]?.[0]||'Pink Runtz'; const feedAction=feedIndex%3===0?'GAS':'PASS'
 return <section className="live-votes shell" id="live-votes">
  <div className="live-votes-head"><div><div className="live-kicker"><span className="live-dot"/> LIVE COMMUNITY <b>GAS OR PASS</b></div><h2>The community is voting <span>right now.</span></h2><p className="muted">Discover strains, make your pick, and watch the community pulse change.</p></div><div className="live-now"><span className="pulse-ring"/> LIVE NOW<strong>{totalLive.toLocaleString()}</strong><small>votes moving in the feed</small></div></div>
  <div className="community-pulse"><div><span className="pulse-icon">✦</span><div><b>COMMUNITY PULSE</b><small>Live activity · Updated while you browse</small></div></div><div className="pulse-stats"><span><strong>{visible.length}</strong> strains live</span><span><strong>{sessionVotes}</strong> your votes</span><span><strong>{sessionVotes?Math.min(100,Math.round(sessionVotes/5)*20):0}%</strong> session progress</span></div></div>
  <div className="live-voter-marquee" aria-live="polite"><div className="live-voter-label"><span className="live-dot"/><b>VOTING LIVE</b></div><div className="live-voter-stream">{voterFeed.length?voterFeed.map((v,i)=><span className="voter-chip" key={`${v.name}-${v.strain}-${i}`}><i>{v.name.slice(0,1).toUpperCase()}</i><b>{v.name}</b><em>{v.action}</em><small>{v.strain}</small></span>):<span className="voter-chip placeholder"><i>✦</i><b>Be the first name on the feed</b><small>Your name appears after your first vote</small></span>}</div></div>
  <div className="live-activity-strip"><span className="live-dot"/><strong>LIVE</strong><span className="activity-avatar">✦</span><span>{activity[feedIndex%activity.length]}</span><em className={feedAction==='GAS'?'gas-text':'pass-text'}>{feedAction}</em><span>on <b>{feedStrain}</b></span></div>
  <div className="vote-controls"><div><b>VOTE FEED</b><small>Choose what you want to see</small></div><div className="canna-vote-filter-v2" role="tablist" aria-label="Vote feed filters"><span role="tab" tabIndex={0} aria-selected={filter==='all'} className={filter==='all'?'is-active':''} onClick={()=>setFilter('all')}>ALL</span><span role="tab" tabIndex={0} aria-selected={filter==='trending'} className={filter==='trending'?'is-active':''} onClick={()=>setFilter('trending')}>🔥 TRENDING</span><span role="tab" tabIndex={0} aria-selected={filter==='my'} className={filter==='my'?'is-active':''} onClick={()=>setFilter('my')}>✦ MY VOTES</span></div></div>
  {lastAction&&<div className="your-vote-toast">✓ {lastAction}</div>}
  {filter==='my'&&visible.length===0?<div className="vote-empty">Cast your first GAS or PASS vote and it will appear here.</div>:<div className="strain-vote-grid">{visible.map(([name,count],i)=>{const choice=strainVotes[name],displayCount=count+(liveBump[name]||0),gas=58+(hash(name)%29),pass=100-gas;return <article className={`strain-vote-card ${choice?'has-vote':''}`} key={name}><span className="strain-rank">#{String(i+1).padStart(3,'0')}</span><div className="strain-art"><img src={photos[hash(name)%photos.length]} alt={`${name} cannabis flower`} loading={i<6?'eager':'lazy'} decoding="async" onError={e=>{const img=e.currentTarget;img.onerror=null;img.src=photos[0]}}/><span>✦ CANNA SOCIAL</span><em>{i<5?'TRENDING':'LIVE'}</em></div><div className="live-card-title"><h3>{name}</h3><p className="live-count"><i/> {displayCount.toLocaleString()} votes <b>• LIVE</b></p></div><div className="mini-signal"><span style={{width:`${gas}%`}}/><b>{gas}% GAS</b></div><div className="gas-pass" style={{position:'relative',zIndex:20,pointerEvents:'auto'}}><button type="button" aria-label={`Vote GAS for ${name}`} className={`gas ${choice==='gas'?'chosen':''}`} disabled={!hydrated||!!choice} style={{position:'relative',zIndex:21,pointerEvents:!hydrated||choice?'none':'auto'}} onClick={e=>{e.preventDefault();e.stopPropagation();openStrainVote(name,'gas')}}>🔥 GAS <b>{gas}%</b></button><button type="button" aria-label={`Vote PASS for ${name}`} className={`pass ${choice==='pass'?'chosen':''}`} disabled={!hydrated||!!choice} style={{position:'relative',zIndex:21,pointerEvents:!hydrated||choice?'none':'auto'}} onClick={e=>{e.preventDefault();e.stopPropagation();openStrainVote(name,'pass')}}>✕ PASS <b>{pass}%</b></button></div>{choice&&<div className="vote-confirm">✓ Your {choice.toUpperCase()} is counted</div>}</article>})}</div>}
  <button type="button" className="strain-more" onClick={()=>setShowAll(!showAll)}>{showAll?'Show less':'Load more live strains →'}</button>
  {pendingVote&&<div id="canna-voter-access" className="voter-gate-backdrop" role="dialog" aria-modal="true" aria-labelledby="voter-gate-title" style={{position:'fixed',inset:0,zIndex:99999,pointerEvents:'auto',display:'grid',placeItems:'center',padding:'20px',background:'rgba(0,0,0,.78)',backdropFilter:'blur(12px)',minHeight:'100dvh',width:'100vw',overflowY:'auto'}}><div className="voter-gate" style={{position:'relative',zIndex:100000,pointerEvents:'auto',maxWidth:'520px',width:'100%'}} onClick={e=>e.stopPropagation()}><div className="voter-gate-star">✦</div><p className="voter-gate-kicker">CANNA SOCIAL · VOTER ACCESS</p><h3 id="voter-gate-title">Confirm before you vote.</h3><p className="voter-gate-copy">Confirm your legal age and choose a screen name. One quick industry question helps us understand the Canna Social community.</p><label className="voter-name-label">SCREEN NAME<input autoFocus value={voterName} maxLength={24} onChange={e=>setVoterName(e.target.value.replace(/[<>]/g,''))} placeholder="Enter a screen name"/></label><label className="voter-name-label" style={{display:'block',marginTop:'18px'}}>WHAT PART OF THE CANNABIS INDUSTRY ARE YOU IN?<select value={voterIndustry} onChange={e=>setVoterIndustry(e.target.value)} style={{width:'100%',height:'58px',minHeight:'58px',padding:'0 46px 0 16px',fontSize:'16px',lineHeight:'1.4',fontWeight:700,letterSpacing:'0',color:'#fff',background:'#141714',border:'1px solid #5a4650',borderRadius:'12px',outline:'none',display:'block',marginTop:'9px',boxSizing:'border-box',appearance:'auto'}}><option value="">Select your industry</option>{industries.map(industry=><option key={industry} value={industry}>{industry}</option>)}</select></label><label className="voter-age-check"><input type="checkbox" checked={ageConfirmed} onChange={e=>setAgeConfirmed(e.target.checked)}/><span>I confirm that I am 21 or older.</span></label><button type="button" className="voter-gate-submit" disabled={!hydrated||!ageConfirmed||!voterName.trim()||!voterIndustry} onClick={e=>{e.preventDefault();e.stopPropagation();submitFirstVote()}}>CONFIRM 21+ &amp; VOTE <span>→</span></button><p className="voter-gate-note">One-time verification during this visit. No email required.</p></div></div>}
  {voteSuccess&&<div className="vote-success-overlay" role="status" aria-live="polite" onClick={()=>setVoteSuccess(null)}><div className="vote-success-card" onClick={e=>e.stopPropagation()}><div className="vote-success-icon">✓</div><div className="vote-success-kicker">VOTE CONFIRMED</div><h3>{voteSuccess.type} COUNTED</h3><p>Your <b>{voteSuccess.type}</b> vote for <strong>{voteSuccess.name}</strong> has been added to the community count.</p><div className="vote-success-stats"><span><b>+1</b><small>YOUR VOTE</small></span><span><b>{sessionVotes}</b><small>YOUR VOTES</small></span></div><button type="button" onClick={()=>setVoteSuccess(null)}>KEEP VOTING →</button></div></div>}
 </section>
}
