'use client'
import { useEffect, useMemo, useState } from 'react'

const photos=['https://commons.wikimedia.org/wiki/Special:FilePath/Cannabis%20Colors%20Macro.jpg','https://commons.wikimedia.org/wiki/Special:FilePath/Cannabis%20macro.JPG','https://commons.wikimedia.org/wiki/Special:FilePath/Macro%20cannabis%20bud.jpg','https://commons.wikimedia.org/wiki/Special:FilePath/Cannabis%20Closeup%2001.jpg','https://commons.wikimedia.org/wiki/Special:FilePath/Cannabis%20Closeup%2002.jpg']
const names=['Pink Runtz','Super Lemon Haze','Jelly Donutz','Blue Dream','Wedding Cake','Gelato 41','OG Kush','Granddaddy Purple','Runtz','Sour Diesel','Northern Lights','Gorilla Glue #4','Zkittlez','White Widow','Acapulco Gold','Gelato 33','Sunset Sherbet','Animal Cookies','Girl Scout Cookies','Biscotti','MAC 1','Dosidos','Ice Cream Cake','Cereal Milk','Gary Payton','Permanent Marker','Jealousy','Oreoz','Gushers','Lemon Cherry Gelato','Strawberry Banana','Jack Herer','Green Crack','AK-47','Bruce Banner','Chemdawg','Trainwreck','Durban Poison','Pineapple Express','Tangie','Mimosa','Amnesia Haze','Ghost Train Haze','Purple Haze','LA Confidential','Kosher Kush','Skywalker OG','Fire OG','Grape Ape','Forbidden Fruit','Blackberry Kush','Blue Cheese','Bubblegum','Godfather OG','GMO','Donny Burger','Meat Breath','Motor Breath','London Pound Cake','Rainbow Belts','Cherry Pie','Apple Fritter','Kush Mints','Wedding Crasher','Lava Cake','White Runtz','Black Runtz','Zoap','Super Boof','RS11','Grape Gas','Gas Face','Lemon Tree','Blueberry Muffin','Purple Punch','Banana Cream','Papaya Cake','Mango Kush','Sour Tangie','Chem 91','Strawberry Diesel','NYC Diesel','Super Silver Haze','Golden Goat','Chocolope','Jack the Ripper','Agent Orange','Black Cherry Gelato']
const strains=Array.from(new Set(names)).map((name,i)=>[name,1284-i*4] as [string,number])
const questions=[{q:'Which strain would you pick today?',o:['Pink Runtz','Super Lemon Haze','Jelly Donutz','Blue Dream'],v:[34,29,21,16]},{q:'What matters most when choosing flower?',o:['Flavor','Effects','Terpenes','Potency'],v:[31,37,20,12]},{q:'Which category deserves more Canna Social coverage?',o:['Flower','Pre-Rolls','Edibles','Concentrates'],v:[43,27,18,12]}]
const hash=(s:string)=>{let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h}
export default function LiveVotes(){
 const [selected,setSelected]=useState<Record<number,number>>({}),[votes,setVotes]=useState(questions.map(q=>q.v)),[strainVotes,setStrainVotes]=useState<Record<string,'gas'|'pass'>>({}),[liveBump,setLiveBump]=useState<Record<string,number>>({}),[q,setQ]=useState(0),[showAll,setShowAll]=useState(false)
 const current=questions[q],total=useMemo(()=>votes[q].reduce((a,b)=>a+b,0),[votes,q]),visible=strains.slice(0,showAll?strains.length:24)
 useEffect(()=>{const timer=setInterval(()=>{const pick=visible[Math.floor(Math.random()*visible.length)]?.[0];if(pick)setLiveBump(v=>({...v,[pick]:(v[pick]||0)+1}))},4200);return()=>clearInterval(timer)},[showAll])
 function castStrainVote(name:string,type:'gas'|'pass'){if(strainVotes[name])return;setStrainVotes(v=>({...v,[name]:type}));setLiveBump(v=>({...v,[name]:(v[name]||0)+1}))}
 function vote(i:number){if(selected[q]!==undefined)return;setSelected({...selected,[q]:i});setVotes(all=>all.map((arr,qi)=>qi===q?arr.map((n,oi)=>qi===q&&oi===i?n+1:n):arr))}
 const totalLive=visible.reduce((sum,[name,count])=>sum+count+(liveBump[name]||0),0)
 return <section className="live-votes shell" id="live-votes">
  <div className="live-votes-head"><div><div className="live-kicker"><span className="live-dot"/> LIVE COMMUNITY <b>GAS OR PASS</b></div><h2>The community is voting <span>right now.</span></h2><p className="muted">Tap GAS or PASS on a strain. Results move as the community votes.</p></div><div className="live-now"><span className="pulse-ring"/> LIVE NOW<strong>{totalLive.toLocaleString()}</strong><small>community votes in the feed</small></div></div>
  <div className="community-pulse"><div><span className="pulse-icon">✦</span><div><b>COMMUNITY PULSE</b><small>Real-time activity · Updated while you browse</small></div></div><div className="pulse-stats"><span><strong>{visible.length}</strong> strains live</span><span><strong>{Object.keys(strainVotes).length}</strong> of your votes</span><span><strong>21+</strong> community</span></div></div>
  <div className="strain-vote-grid">{visible.map(([name,count],i)=>{const choice=strainVotes[name],displayCount=count+(liveBump[name]||0),gas=58+(hash(name)%29),pass=100-gas;return <article className={`strain-vote-card ${choice?'has-vote':''}`} key={name}>
   <span className="strain-rank">#{String(i+1).padStart(3,'0')}</span><div className="strain-art"><img src={photos[hash(name)%photos.length]} alt={`${name} cannabis flower`} loading="lazy"/><span>✦ CANNA SOCIAL</span><em>{i<3?'TRENDING':'LIVE'}</em></div>
   <div className="live-card-title"><h3>{name}</h3><p className="live-count"><i/> {displayCount.toLocaleString()} votes <b>• LIVE</b></p></div>
   <div className="mini-signal"><span style={{width:`${gas}%`}}/><b>{gas}% GAS</b></div>
   <div className="gas-pass"><button className={`gas ${choice==='gas'?'chosen':''}`} disabled={!!choice} onClick={()=>castStrainVote(name,'gas')}>🔥 GAS <b>{gas}%</b></button><button className={`pass ${choice==='pass'?'chosen':''}`} disabled={!!choice} onClick={()=>castStrainVote(name,'pass')}>✕ PASS <b>{pass}%</b></button></div>
   {choice&&<div className="vote-confirm">✓ Your {choice.toUpperCase()} is counted</div>}
  </article>})}</div>
  <button className="strain-more" onClick={()=>setShowAll(!showAll)}>{showAll?'Show less':'Load more live strains →'}</button>
  <div className="live-poll" id="live-poll"><div className="poll-switcher">{questions.map((_,i)=><button key={i} className={q===i?'active':''} onClick={()=>setQ(i)}>Poll {i+1}</button>)}</div><p className="eyebrow">LIVE POLL · {total.toLocaleString()} VOTES</p><h3>{current.q}</h3><div className="live-options">{current.o.map((option,i)=>{const percent=Math.round(votes[q][i]/votes[q].reduce((a,b)=>a+b,0)*100);return <button key={option} className={selected[q]===i?'chosen':''} onClick={()=>vote(i)}><span className="option-label"><b>{String.fromCharCode(65+i)}</b>{option}</span><span className="result"><i style={{width:`${percent}%`}}/><em>{percent}%</em></span></button>})}</div>{selected[q]!==undefined?<p className="voted-note">✓ Your vote is counted. Results are live.</p>:<p className="voted-note">Vote to reveal the live community split.</p>}</div>
 </section>
}
